# Routing Schema
#
# /projects
#   Homepage of the project repository

# /search
#   general search functionality: one interface which combines all searchable
#   items (projects, users, organizations, ...)

# /project/*
#   project management and utility functionality

# /org/*
#   organization management. No user-defined pages in this namespace.

# /user/*
#   user management, such as login, logout, OAuth connect, etc.
#   No user-defined pages in this namespace.

# /*
#   Most frequently used pages to display users, organizations and projects.
#   This namespace contains mainly pages with user-defined names (usernames,
#   organization names, project names), so special care must be taken to avoid
#   namespace collisions.




# Project repository homepage
librecores_project_repo_homepage:
    path:     /projects
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:index }

# Unified search: users, organizations and projects
librecores_project_repo_project_search:
    path:     /search
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:search }



# Project management pages
librecores_project_repo_project_new:
    path:     /project/new
    defaults: { _controller: LibrecoresProjectRepoBundle:Project:new }

# XXX: this is not yet implemented - same as project repository homepage?
#librecores_project_repo_project_list:
#    path:     /project/list
#    defaults: { _controller: LibrecoresProjectRepoBundle:Project:list }



# User management pages
# most /user/XXX routes are defined in app/config/routing.yml in the
# FOSUserBundle routes.



# Organization management pages
librecores_project_repo_organization_new:
    path:     /org/new
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:new }

librecores_project_repo_organization_list:
    path:     /org/list
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:list }

# XXX: THE ORG ROUTES BELOW SHOULD BE RECONSIDERED/MERGED

# Organization Routes
# XXX: what about moving these actions inside the organization view or settings
# pages and to avoid having almost-empty pages?
librecores_project_repo_organization_remove:
    path:     /org/{organizationName}/remove
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:remove }

librecores_project_repo_organization_join:
    path:     /org/{organizationName}/join
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:join }

librecores_project_repo_organization_leave:
    path:     /org/{organizationName}/leave
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:leave }

librecores_project_repo_organization_approve:
    path:     /org/{organizationName}/{userName}/approve
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:approve }

librecores_project_repo_organization_deny:
    path:     /org/{organizationName}/{userName}/deny
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:deny }




# User/Organization view pages
librecores_project_repo_user_org_view:
    path:     /{userOrOrganization}
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:userOrgView }

librecores_project_repo_user_org_settings:
    path:     /{userOrOrganization}/settings
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:userOrgSettings }

librecores_project_repo_organization_requests:
    path:     /{organizationName}/settings/joinrequests
    defaults: { _controller: LibrecoresProjectRepoBundle:Organization:requests }



# Project pages
librecores_project_repo_project_view:
    path:     /{parentName}/{projectName}
    defaults: { _controller: LibrecoresProjectRepoBundle:Project:view }

librecores_project_repo_project_settings:
    path:     /{parentName}/{projectName}/settings
    defaults: { _controller: LibrecoresProjectRepoBundle:Project:settings }

librecores_project_repo_project_settings_team:
    path:     /{parentName}/{projectName}/settings/team
    defaults: { _controller: LibrecoresProjectRepoBundle:Project:settingsTeam }



# Redirect trailing slash
# http://symfony.com/doc/current/routing/redirect_trailing_slash.html
librecores_project_repo_remove_trailing_slash:
    path:     /{url}
    defaults: { _controller: LibrecoresProjectRepoBundle:Default:removeTrailingSlash }
    requirements:
        url:  .*/$
    methods:  [GET]
