parameters:
    librecores_user_provider.class: Librecores\ProjectRepoBundle\Security\Core\User\FOSUBUserProvider
    librecores_user_manager.class:  Librecores\ProjectRepoBundle\Doctrine\UserManager

    projectrepo.util.github_url:  'https://github.com/'
    projectrepo.util.shields_url: 'https://img.shields.io/github/'
    projectrepo.util.shields_ext: 'svg'

services:
    update_project_info_service:
        class: Librecores\ProjectRepoBundle\Consumer\UpdateProjectInformation
        arguments:
            - @logger
            - @doctrine
            - @markdown.parser

    app.form.type.project:
        class: Librecores\ProjectRepoBundle\Form\Type\ProjectType
        tags:
            - { name: form.type, alias: project }

    app.form.type.organization:
        class: Librecores\ProjectRepoBundle\Form\Type\OrganizationType
        tags:
            - { name: form.type, alias: organization }

    librecores_user_manager:
        class: Librecores\ProjectRepoBundle\Doctrine\UserManager
        arguments: ['@fos_user.util.password_updater', '@fos_user.util.canonical_fields_updater', '@fos_user.object_manager', '%fos_user.model.user.class%']

    librecores_user_provider:
        class: "%librecores_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager, {github: oauth_user_id, google: oauth_user_id}]

    librecores_project_voter:
        class: Librecores\ProjectRepoBundle\Security\ProjectVoter
        tags:
            - { name: security.voter }
        public: false

    librecores.form_extention.icon:
        class: Librecores\ProjectRepoBundle\Form\Extension\ButtonTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
            
    validator.user_org_name:
        class: Librecores\ProjectRepoBundle\Validator\Constraints\UserOrgNameValidator
        arguments:
            - @doctrine
            - @router
        tags:
            - { name: validator.constraint_validator }

    projectrepo.util.github:
        class: Librecores\ProjectRepoBundle\Util\GitHubUtil
        arguments:
            - '%projectrepo.util.github_url%'
            - '%projectrepo.util.shields_url%'
            - '%projectrepo.util.shields_ext%'

#    librecores_project_repo.example:
#        class: Librecores\ProjectRepoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
