# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: legacy_aliases.yml }


services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/Librecores/ProjectRepoBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Librecores\ProjectRepoBundle\:
        resource: '../../../ProjectRepoBundle/*'
        exclude: '../../../ProjectRepoBundle/{Entity,Repository}' #Form/Type/PurifiedTextareaType.php
    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Librecores\ProjectRepoBundle\Controller\:
            resource: '../../../ProjectRepoBundle/Controller'
            public: true
            tags: ['controller.service_arguments']

    # Consumer Services (called through RabbitMQ)
    Librecores\ProjectRepoBundle\Consumer\UpdateProjectInformation:

    # Utilities
    Librecores\ProjectRepoBundle\Util\MarkupToHtmlConverter:

    Librecores\ProjectRepoBundle\Util\GithubApiService:

    Librecores\ProjectRepoBundle\Util\QueueDispatcherService:
        calls:
            - [setContainer, ['@service_container']]

    # Forms
    Librecores\ProjectRepoBundle\Form\Type\ProjectType:
        tags:
            - { name: form.type, alias: project }

    Librecores\ProjectRepoBundle\Form\Type\OrganizationType:
        tags:
            - { name: form.type, alias: organization }

    Librecores\ProjectRepoBundle\Form\Extension\ButtonTypeIconExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

    Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer:

    Symfony\Component\Form\DataTransformerInterface: '@Exercise\HTMLPurifierBundle\Form\HTMLPurifierTransformer'

    Librecores\ProjectRepoBundle\Form\Type\PurifiedTextareaType:
        tags:
            - { name: form.type, alias: purified_textarea }

    Librecores\ProjectRepoBundle\Validator\Constraints\UserOrgNameValidator:
        tags:
            - { name: validator.constraint_validator }

    FOS\UserBundle\Util\PasswordUpdaterInterface  : '@fos_user.util.password_updater'
    FOS\UserBundle\Util\CanonicalFieldsUpdater: '@fos_user.util.canonical_fields_updater'
    Doctrine\Common\Persistence\ObjectManager: '@fos_user.object_manager'

    # User/auth management
    Librecores\ProjectRepoBundle\Doctrine\UserManager:
        arguments:
          $class: '%fos_user.model.user.class%'

    # Librecores\ProjectRepoBundle\Doctrine\UserManager: '@fos_user.user_manager'
    Symfony\Component\Validator\Validator\TraceableValidator: '@validator'

    Librecores\ProjectRepoBundle\Security\Core\User\LibreCoresUserProvider:
        arguments:
            $userManager: '@fos_user.user_manager'
            $session: '@session'

    # Librecores\ProjectRepoBundle\Security\Core\User\LibreCoresUserProvider: '@librecores_user_provider'

    Librecores\ProjectRepoBundle\EventListener\OAuthRegistrationListener:
        arguments:
            $userManager: '@fos_user.user_manager'
            $session: '@session'
        tags:
            - { name: kernel.event_subscriber }

    # Security
    Librecores\ProjectRepoBundle\Security\ProjectVoter:
        tags:
            - { name: security.voter }

    Librecores\ProjectRepoBundle\Repository\ContributorRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - Librecores\ProjectRepoBundle\Entity\Contributor

    Librecores\ProjectRepoBundle\Repository\CommitRepository:
        factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
        arguments:
            - Librecores\ProjectRepoBundle\Entity\Commit

    Librecores\ProjectRepoBundle\Util\ProcessCreator: ~

    Librecores\ProjectRepoBundle\RepoCrawler\RepoCrawlerFactory:

    Librecores\ProjectRepoBundle\Doctrine\ProjectMetricsProvider:

    Librecores\ProjectRepoBundle\Entity\Organization:

    Librecores\ProjectRepoBundle\Entity\User:
