imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    # avoid garbage collection not being able to access the session dir
    # Notice: SessionHandler::gc(): ps_files_cleanup_dir: 
    # opendir(/var/lib/php/sessions) failed: Permission denied (13) 
    session:
        gc_probability: 0

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

easy_admin:
    site_name: 'LibreCores Admin'
    design:
        form_theme:   'horizontal'
        color_scheme: 'dark'
    entities:
        - Librecores\ProjectRepoBundle\Entity\GitSourceRepo
        - Librecores\ProjectRepoBundle\Entity\Organization
        - Librecores\ProjectRepoBundle\Entity\OrganizationMember
        - Librecores\ProjectRepoBundle\Entity\Project
#        - Librecores\ProjectRepoBundle\Entity\SourceStats
#        - Librecores\ProjectRepoBundle\Entity\SourceStatsAuthor
#        - Librecores\ProjectRepoBundle\Entity\SourceStatsCommitHistogram
        - Librecores\ProjectRepoBundle\Entity\User
