# HWIOAuthBundle
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /user/connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /user/connect

hwi_oauth_connect:
     resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
     prefix: /user/connect

github_login:
    path: /user/connect/check-github

google_login:
    path: /user/connect/check-google

# FOSUser
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /user

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# Site routes ("static content")
librecores_site:
    resource: "@LibrecoresSiteBundle/Resources/config/routing.yml"
    prefix:   /static

# Planet routes
librecores_planet:
    resource: "@LibrecoresPlanetBundle/Resources/config/routing.yml"
    prefix:   /planet

# Project Repository Routes
librecores_project_repo:
    resource: "@LibrecoresProjectRepoBundle/Resources/config/routing.yml"
    prefix:   /
