# HWIOAuthBundle
annotation:
    resource: 'routes/annotation.yml'

hwi_oauth_routing:
    resource: 'routes/hwi_oauth.yml'

fos_user_routing:
    resource: 'routes/fos_user.yml'

librecores_planet:
    resource: "routes/planet.yml"

# Project Repository Routes
librecores_project_repo:
    resource: 'routes/project_repo.yml'

github_login:
    path: /user/connect/check-github

google_login:
    path: /user/connect/check-google

librecores.user.settings.oauth-disconnect:
    path: /user/disconnect/{serviceName}
    controller: App\Controller\UserController::disconnectFromOAuthServiceAction

librecores.user.settings.profile:
    path: /user/settings/profile
    controller: App\Controller\UserController::profileSettingsAction

librecores.user.settings.connections:
    path: /user/settings/connected-services
    controller: App\Controller\UserController::connectionsSettingsAction

librecores.user.settings.password:
    path: /user/settings/password
    controller: App\Controller\UserController::passwordSettingsAction

librecores_user_resend_confirmation:
    path: /user/resend-confirmation
    controller: App\Controller\UserController::resendConfirmationEmailAction
