security:
    encoders:
        # Passwords are hashed using bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            # Allow login with username or email address
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /user/login
                check_path: /user/login_check
            oauth:
                resource_owners:
                    github: "/user/connect/check-github"
                    google: "/user/connect/check-google"
                login_path: /user/login
                failure_path: /user/register

                oauth_user_provider:
                    service: librecores_user_provider

            logout:
                path: /user/logout
                # After logout, the user is redirected to this path.
                target: /
            anonymous:    true
            logout_on_user_change: true

        login:
            pattern:  ^/user/login$
            security: false

            remember_me:
                secret: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        # only admins should be able to access the easy admin panel
        - { path: ^/admin, role: ROLE_ADMIN }

        # login and registration pages should work for non-logged-in users
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resend-confirmation, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # all other user setting functionality requires a login
        - { path: ^/user/.+$, role: IS_AUTHENTICATED_FULLY }

        # users need to be logged in to create a new project or organization
        - { path: ^/project/new$, role: ROLE_USER }
        - { path: ^/org/new$, role: ROLE_USER }

        # and of course to edit any settings
        # additional fine-grained checks are done inside the controllers
        - { path: ^/[^/]+/settings, role: ROLE_USER }
