old_sound_rabbit_mq:
    connections:
        default:
            host:     "%rabbitmq_host%"
            port:     "%rabbitmq_port%"
            user:     "%rabbitmq_user%"
            password: "%rabbitmq_password%"
            vhost:    '/'
            lazy:     true
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        update_project_info:
            connection:       default
            exchange_options: {name: 'update-project-info', type: fanout}
        send_notification:
            connection:       default
            exchange_options: {name: 'send-notification', type: fanout}
    consumers:
        update_project_info:
            connection:       default
            exchange_options: {name: 'update-project-info', type: fanout}
            queue_options:    {name: 'update-project-info'}
            callback:         update_project_info_consumer
        update_github_metadata:
            connection:       default
            exchange_options: {name: 'update-project-info', type: fanout}
            queue_options:    {name: 'update-github-metadata'}
            callback:         update_github_metadata_consumer
        web_notification:
            connection:       default
            exchange_options: {name: 'send-notification', type: fanout}
            queue_options:    {name: 'send-notification'}
            callback:         web_notification_consumer
        email_notification:
            connection:       default
            exchange_options: {name: 'send-notification', type: fanout}
            queue_options:    {name: 'send-notification'}
            callback:         email_notification_consumer
