swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:       "%mailer_host%"
    port:       "%mailer_port%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
