dist: trusty
sudo: false

language: php
php:
  - '7.1'
env:
  - SYMFONY_ENV=test

git:
  depth: 1

cache:
  directories:
   - site/vendor

install:
  - cd site && composer install --no-scripts --ignore-platform-reqs

script:
  - ./vendor/bin/phpunit


