---
# GitHub OAuth secrets
# get it from https://github.com/settings/applications/
site_github_app_id: "INSERT_OAUTH_ID_HERE"
site_github_app_secret: "INSERT_OAUTH_SECRET_HERE"

# Google OAuth secrets (optional, will disable Google login)
# Create a new google login project
site_google_app_id: ~
site_google_app_secret: ~

# SMTP configuration for outbound transactional mail (optional)
# You can use your own email server, gmail SMTP or providers like Sendgrid
site_smtp_host: ~
site_smtp_port: 465
site_smtp_encryption: 'ssl' # options: tls, ssl, login
site_smtp_user: ~
site_smtp_password: ~

# Algolia
# Sign Up with Algolia, create a community project and generate the API keys
site_algolia_app_id: 'INSERT_ALGOLIA_APP_ID_HERE'
site_algolia_api_key: 'INSERT_ALGOLIA_API_KEY_HERE'
site_algolia_search_key: 'INSERT_ALGOLIA_SEARCH_KEY_HERE'
