---
# PHP version to be used
# Packages are expected to be named php<php_version>, e.g. php7.0, php7.0-xml,
# etc. The same is true for the binaries. Use quotes to ensure it's a string!
php_version: "7.4"

# PHP extensions, installed from OS packages (preferred)
# All packages are expected to be named "php{{ php_version }}-EXTENSION_NAME"
php_extensions_packaged:
  - dev
  - curl
  - mysql
  - xml
  - bcmath
  - mbstring
  - zip
  - intl
  - gd

# Development extensions installed through OS packages
# Like php_extensions_packaged, but only available during development
php_devel_extensions_packaged:
  - xdebug

# PHP extensions, installed through PEAR (if not available through OS packages)
php_extensions_pecl: []
#  - { name: "NAME", package: "pecl.php.net/NAME" }

# PHP FPM socket (for web servers)
php_fpm_sock: "/var/run/php/php{{ php_version }}-fpm.sock"

# Version of composer to install
# See https://getcomposer.org/download/ for available versions
composer_version: "2.0.8"

# Major version of nodejs to be used
nodejs_major_version: 10

# RabbitMQ consumers started as service (through the Symfony rabbitmq bundle)
# Uses the rabbitmq:consumer/rabbitmq:multiple-consumer console commands.
rabbitmq_consumers:
  - name: update_project_info
    type: single
  - name: update_github_metadata
    type: single
  - name: notification
    type: multiple

# Options passed to the RabbitMQ consumer services
# Consume 1 message per run, allow up to 256 MB of memory for this process
# Consuming more than one message improves performance, but can lead to
# hard-to-debug caching problems around Doctrine.
rabbitmq_consumer_options: -vv --memory-limit 256 --messages 1
