---
# Install PHP for the web server
- name: Add PHP ppa repository
  apt_repository: repo='ppa:ondrej/php'

- name: Install PHP FPM
  become: true
  apt:  package=php{{ php_version }}-fpm state=installed

- name: Setup support for PHP in nginx
  become: true
  template: src=nginx/upstream_php.conf.tpl dest=/etc/nginx/conf.d/upstream_php{{ php_version }}.conf
  notify: restart nginx

- name: Install PHP CLI
  become: true
  apt:  package=php{{ php_version }}-cli state=installed

# OS packaged PHP extensions
- name: Install packaged PHP extensions
  become: true
  apt:  package=php{{php_version}}-{{ item }} state=installed
  with_items: "{{ php_extensions_packaged }}"

- name: Enable packaged PHP extensions for all SAPIs
  become: true
  # creates= only accepts one file; phpenmod also creates the fpm symlink
  command: /usr/sbin/phpenmod -s ALL {{ item }} creates=/etc/php/{{ php_version }}/cli/conf.d/20-{{ item }}.ini
  with_items: "{{ php_extensions_packaged }}"
  notify: restart php-fpm

- name: Install packaged PHP extensions for development
  become: true
  apt:  package=php{{php_version}}-{{ item }} state=installed
  with_items: "{{ php_devel_extensions_packaged }}"

- name: Enable packaged PHP extensions for development for all SAPIs
  become: true
  # creates= only accepts one file; phpenmod also creates the fpm symlink
  command: /usr/sbin/phpenmod -s ALL {{ item }} creates=/etc/php/{{ php_version }}/cli/conf.d/20-{{ item }}.ini
  with_items: "{{ php_devel_extensions_packaged }}"
  notify: restart php-fpm

# PHP extensions from PECL
- name: Install PECL-installed PHP extensions
  become: true
  shell: echo "\n" | /usr/bin/pecl install {{ item.package }} creates=/usr/lib/php/20151012/{{ item.name }}.so
  with_items: "{{ php_extensions_pecl }}"

- name: Configure PECL-installed PHP extensions
  become: true
  template: src=php_extension.tpl dest=/etc/php/mods-available/{{ item.name }}.ini
  with_items: "{{ php_extensions_pecl }}"

- name: Enable PECL-installed PHP extensions for all SAPIs (through PECL)
  become: true
  # creates= only accepts one file; phpenmod also creates the fpm symlink
  command: /usr/sbin/phpenmod -s ALL {{ item.name }} creates=/etc/php/{{ php_version }}/cli/conf.d/20-{{ item.name }}.ini
  with_items: "{{ php_extensions_pecl }}"
  notify: restart php-fpm

# Composer
- name:  Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  args:
    creates: /usr/bin/composer
