---
# Install RabbitMQ
# see http://www.rabbitmq.com/install-debian.html

- name: Add RabbitMQ repository
  shell: echo 'deb http://www.rabbitmq.com/debian/ testing main' > /etc/apt/sources.list.d/rabbitmq.list creates=/etc/apt/sources.list.d/rabbitmq.list

- name: Download RabbitMQ key
  get_url: url=https://www.rabbitmq.com/rabbitmq-release-signing-key.asc dest=/tmp/rabbitmq-release-signing-key.asc

- name: Add RabbitMQ key
  become: true
  command: apt-key add /tmp/rabbitmq-release-signing-key.asc

- name: Update apt again
  become: true
  apt:  update_cache=yes

- name: Install RabbitMQ
  become: true
  apt:  pkg=rabbitmq-server state=installed

- name: Enable RabbitMQ plugins
  shell: rabbitmq-plugins enable rabbitmq_management

- name: Add admin user
  shell: rabbitmqctl add_user admin {{ rabbitmq_admin_password }}
  ignore_errors: true

- name: Set admin user tags
  shell: rabbitmqctl set_user_tags admin administrator
  ignore_errors: true

- name: Set admin user permissions
  shell: rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  ignore_errors: true

- name: Delete guest user
  shell: rabbitmqctl delete_user guest
  notify: restart rabbitmq
  ignore_errors: true

- name: Add librecores user
  shell: rabbitmqctl add_user librecores {{ site_rabbitmq_password }}
  ignore_errors: true

- name: Set admin user permissions
  shell: rabbitmqctl set_permissions -p / librecores ".*" ".*" ".*"
  ignore_errors: true
