---
# Install RabbitMQ
# see http://www.rabbitmq.com/install-debian.html

- name: Add RabbitMQ and Erlang key
  become: true
  apt_key:
    url: "{{item}}"
  with_items:
    - 'https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey'
    - 'https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc'

- name: Add RabbitMQ and Erlang repository
  become: true
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - 'deb http://packages.erlang-solutions.com/ubuntu xenial contrib'
    - 'deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ xenial main'

- name: Install RabbitMQ
  become: true
  apt:  pkg=rabbitmq-server state=present

- name: Enable RabbitMQ plugins
  shell: rabbitmq-plugins enable rabbitmq_management

- name: Add admin user
  shell: rabbitmqctl add_user admin {{ rabbitmq_admin_password }}
  ignore_errors: true

- name: Set admin user tags
  shell: rabbitmqctl set_user_tags admin administrator
  ignore_errors: true

- name: Set admin user permissions
  shell: rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  ignore_errors: true

- name: Delete guest user
  shell: rabbitmqctl delete_user guest
  notify: restart rabbitmq
  ignore_errors: true

- name: Add librecores user
  shell: rabbitmqctl add_user librecores {{ site_rabbitmq_password }}
  ignore_errors: true

- name: Set admin user permissions
  shell: rabbitmqctl set_permissions -p / librecores ".*" ".*" ".*"
  ignore_errors: true
