---
# Install RabbitMQ
# see http://www.rabbitmq.com/install-debian.html

- name: Add RabbitMQ bintray repository key
  become: true
  apt_key:
    url: "{{item}}"
  with_items:
    - 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc'

- name: Add RabbitMQ and Erlang repositories (maintained by RabbitMQ)
  become: true
  apt_repository:
    repo: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - 'deb https://dl.bintray.com/rabbitmq-erlang/debian xenial erlang-21.x'
    - 'deb https://dl.bintray.com/rabbitmq/debian xenial main'

- name: Use Erlang packages from RabbitMQ, not from Ubuntu
  copy:
    dest: /etc/apt/preferences.d/erlang
    content: |
      Package: erlang*
      Pin: release o=Bintray
      Pin-Priority: 1000

- name: Install RabbitMQ
  become: true
  apt:  pkg=rabbitmq-server state=present

- name: Enable RabbitMQ plugins
  shell: rabbitmq-plugins enable rabbitmq_management

- name: Add admin user
  shell: rabbitmqctl add_user admin {{ rabbitmq_admin_password }}
  ignore_errors: true

- name: Set admin user tags
  shell: rabbitmqctl set_user_tags admin administrator
  ignore_errors: true

- name: Set admin user permissions
  shell: rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
  ignore_errors: true

- name: Delete guest user
  shell: rabbitmqctl delete_user guest
  notify: restart rabbitmq
  ignore_errors: true

- name: Add librecores user
  shell: rabbitmqctl add_user librecores {{ site_rabbitmq_password }}
  ignore_errors: true

- name: Set admin user permissions
  shell: rabbitmqctl set_permissions -p / librecores ".*" ".*" ".*"
  ignore_errors: true
