# Routing Schema
#
# /projects
#   Homepage of the project repository

# /search
#   general search functionality: one interface which combines all searchable
#   items (projects, users, organizations, ...)

# /project/*
#   project management and utility functionality

# /org/*
#   organization management. No user-defined pages in this namespace.

# /user/*
#   user management, such as login, logout, OAuth connect, etc.
#   No user-defined pages in this namespace.

# /*
#   Most frequently used pages to display users, organizations and projects.
#   This namespace contains mainly pages with user-defined names (usernames,
#   organization names, project names), so special care must be taken to avoid
#   namespace collisions.




# Project repository homepage
librecores_project_repo_homepage:
    path:     /
    controller: App\Controller\IndexController::homeAction

# Unified search: users, organizations and projects
librecores_project_repo_project_search:
    path:     /search
    controller: App\Controller\DefaultController::searchAction

# Project/Organization management pages
librecores_project_repo_project_new:
    path:     /project/new
    controller: App\Controller\ProjectController::newAction

librecores_project_repo_project_list:
    path:     /project/list
    controller: App\Controller\ProjectController::listAction

#  management pages
librecores_project_repo_organization_new:
    path:     /org/new
    controller: App\Controller\OrganizationController::newAction

librecores_project_repo_organization_list:
    path:     /org/list
    controller: App\Controller\OrganizationController::listAction



# User/Organization view routes
librecores_project_repo_user_org_view:
    path:     /{userOrOrganization}
    controller: App\Controller\DefaultController::userOrgViewAction

librecores_project_repo_user_org_settings:
    path:     /{userOrOrganization}/settings
    controller: App\Controller\DefaultController::userOrgSettingsAction



# Project routes

librecores_project_repo_project_view:
    path:     /{parentName}/{projectName}
    controller: App\Controller\ProjectController::viewAction

librecores_project_repo_project_settings:
    path:     /{parentName}/{projectName}/settings
    controller: App\Controller\ProjectController::settingsAction

librecores_project_repo_project_update:
    path: /{parentName}/{projectName}/update
    controller: App\Controller\ProjectController::updateAction

librecores_project_repo_project_status:
    path: /{parentName}/{projectName}/crawl_status
    controller: App\Controller\ProjectController::crawlStatusAction

librecores_project_repo_project_dismiss_alert:
    path: /{parentName}/{projectName}/dismiss_alert
    controller: App\Controller\ProjectController::dismissAlertAction


# Organization routes

librecores_project_repo_organization_view:
    path:     /{organizationName}
    controller: App\Controller\OrganizationController::viewAction

librecores_project_repo_organization_settings:
    path:     /{organizationName}/settings
    controller: App\Controller\OrganizationController::settingsAction

librecores_project_repo_organization_settings_delete:
    path:     /{organizationName}/settings/delete
    controller: App\Controller\OrganizationController::deleteAction

librecores_project_repo_organization_settings_join:
    path:     /{organizationName}/settings/join
    controller: App\Controller\OrganizationController::joinAction

librecores_project_repo_organization_settings_leave:
    path:     /{organizationName}/settings/leave
    controller: App\Controller\OrganizationController::leaveAction

librecores_project_repo_organization_settings_approve:
    path:     /{organizationName}/settings/approve/{userName}
    controller: App\Controller\OrganizationController::approveAction

librecores_project_repo_organization_settings_deny:
    path:     /{organizationName}/settings/deny/{userName}
    controller: App\Controller\OrganizationController::denyAction

librecores_project_repo_organization_settings_remove:
    path:     /{organizationName}/settings/remove/{userName}
    controller: App\Controller\OrganizationController::removeAction



# User management pages
# most /user/XXX routes are defined in app/config/routing.yml in the
# FOSUserBundle routes.



# Redirect trailing slash
# http://symfony.com/doc/current/routing/redirect_trailing_slash.html
librecores_project_repo_remove_trailing_slash:
    path:     /{url}
    controller: App\Controller\DefaultController::removeTrailingSlashAction
    requirements:
        url:  .*/$
    methods:  [GET]
