---
# Development environment on a single machine with dummy credentials
- hosts: all
  become: true
  roles:
    - dev-vagrant
  vars_files:
    - "vars/dev-vagrant.yml"
    - "secrets/dev-vagrant.secrets.yml"
