---
# Development environment on a single machine with dummy credentials
- hosts: all
  sudo: yes
  roles:
    - dev-vagrant
  vars_files:
    - "vars/dev-vagrant.yml"
    - "vars/dev-vagrant.secrets.yml"

