---
# Production environment on AWS: reset all data
- name: Deploy librecores.org on AWS
#  hosts: tag_group_librecores_staging
  hosts: staging
  gather_facts: true
  user: ubuntu
  become: true
  roles:
    - resetdata
  vars_files:
    - "vars/production-aws.yml"
    - "secrets/production-aws.secrets.yml"
