---
# Production environment on AWS: initialize data from fixtures
- name: Deploy librecores.org on AWS
#  hosts: tag_group_librecores_staging
  hosts: production
  gather_facts: true
  user: ubuntu
  become: true
  roles:
    - initdata
  vars_files:
    - "vars/production-aws.yml"
    - "secrets/production-aws.secrets.yml"
